/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * SkillSwap API - Peer-to-peer skill exchange platform
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AuthResponse,
  BookSessionRequest,
  CreateRatingRequest,
  CreateSkillRequest,
  ErrorResponse,
  GetMySessionsParams,
  GetSkillsParams,
  HealthStatus,
  LoginRequest,
  MentorMatch,
  Rating,
  RegisterRequest,
  Session,
  Skill,
  Transaction,
  UpdateProfileRequest,
  UserProfile,
  Wallet,
} from "./api.schemas.ts";

import { customFetch } from "./custom-fetch.ts";
import type { ErrorType, BodyType } from "./custom-fetch.ts";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Register a new user
 */
export const getRegisterUserUrl = () => {
  return `/api/auth/register`;
};

export const registerUser = async (
  registerRequest: RegisterRequest,
  options?: RequestInit,
): Promise<AuthResponse> => {
  return customFetch<AuthResponse>(getRegisterUserUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(registerRequest),
  });
};

export const getRegisterUserMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerUser>>,
    TError,
    { data: BodyType<RegisterRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerUser>>,
  TError,
  { data: BodyType<RegisterRequest> },
  TContext
> => {
  const mutationKey = ["registerUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerUser>>,
    { data: BodyType<RegisterRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return registerUser(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerUser>>
>;
export type RegisterUserMutationBody = BodyType<RegisterRequest>;
export type RegisterUserMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Register a new user
 */
export const useRegisterUser = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerUser>>,
    TError,
    { data: BodyType<RegisterRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof registerUser>>,
  TError,
  { data: BodyType<RegisterRequest> },
  TContext
> => {
  return useMutation(getRegisterUserMutationOptions(options));
};

/**
 * @summary Login with email and password
 */
export const getLoginUserUrl = () => {
  return `/api/auth/login`;
};

export const loginUser = async (
  loginRequest: LoginRequest,
  options?: RequestInit,
): Promise<AuthResponse> => {
  return customFetch<AuthResponse>(getLoginUserUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(loginRequest),
  });
};

export const getLoginUserMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginUser>>,
    TError,
    { data: BodyType<LoginRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginUser>>,
  TError,
  { data: BodyType<LoginRequest> },
  TContext
> => {
  const mutationKey = ["loginUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginUser>>,
    { data: BodyType<LoginRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return loginUser(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginUser>>
>;
export type LoginUserMutationBody = BodyType<LoginRequest>;
export type LoginUserMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Login with email and password
 */
export const useLoginUser = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginUser>>,
    TError,
    { data: BodyType<LoginRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof loginUser>>,
  TError,
  { data: BodyType<LoginRequest> },
  TContext
> => {
  return useMutation(getLoginUserMutationOptions(options));
};

/**
 * @summary Get current user profile
 */
export const getGetMeUrl = () => {
  return `/api/users/me`;
};

export const getMe = async (options?: RequestInit): Promise<UserProfile> => {
  return customFetch<UserProfile>(getGetMeUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMeQueryKey = () => {
  return [`/api/users/me`] as const;
};

export const getGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({
    signal,
  }) => getMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMe>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>;
export type GetMeQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get current user profile
 */

export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMeQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update current user profile
 */
export const getUpdateMeUrl = () => {
  return `/api/users/me`;
};

export const updateMe = async (
  updateProfileRequest: UpdateProfileRequest,
  options?: RequestInit,
): Promise<UserProfile> => {
  return customFetch<UserProfile>(getUpdateMeUrl(), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateProfileRequest),
  });
};

export const getUpdateMeMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMe>>,
    TError,
    { data: BodyType<UpdateProfileRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateMe>>,
  TError,
  { data: BodyType<UpdateProfileRequest> },
  TContext
> => {
  const mutationKey = ["updateMe"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateMe>>,
    { data: BodyType<UpdateProfileRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return updateMe(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMeMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateMe>>
>;
export type UpdateMeMutationBody = BodyType<UpdateProfileRequest>;
export type UpdateMeMutationError = ErrorType<unknown>;

/**
 * @summary Update current user profile
 */
export const useUpdateMe = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMe>>,
    TError,
    { data: BodyType<UpdateProfileRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateMe>>,
  TError,
  { data: BodyType<UpdateProfileRequest> },
  TContext
> => {
  return useMutation(getUpdateMeMutationOptions(options));
};

/**
 * @summary Get a user's public profile
 */
export const getGetUserByIdUrl = (userId: number) => {
  return `/api/users/${userId}`;
};

export const getUserById = async (
  userId: number,
  options?: RequestInit,
): Promise<UserProfile> => {
  return customFetch<UserProfile>(getGetUserByIdUrl(userId), {
    ...options,
    method: "GET",
  });
};

export const getGetUserByIdQueryKey = (userId: number) => {
  return [`/api/users/${userId}`] as const;
};

export const getGetUserByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserById>>,
  TError = ErrorType<ErrorResponse>,
>(
  userId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getUserById>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserByIdQueryKey(userId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserById>>> = ({
    signal,
  }) => getUserById(userId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!userId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserById>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetUserByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserById>>
>;
export type GetUserByIdQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get a user's public profile
 */

export function useGetUserById<
  TData = Awaited<ReturnType<typeof getUserById>>,
  TError = ErrorType<ErrorResponse>,
>(
  userId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getUserById>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetUserByIdQueryOptions(userId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get all skills
 */
export const getGetSkillsUrl = (params?: GetSkillsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/skills?${stringifiedParams}`
    : `/api/skills`;
};

export const getSkills = async (
  params?: GetSkillsParams,
  options?: RequestInit,
): Promise<Skill[]> => {
  return customFetch<Skill[]>(getGetSkillsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetSkillsQueryKey = (params?: GetSkillsParams) => {
  return [`/api/skills`, ...(params ? [params] : [])] as const;
};

export const getGetSkillsQueryOptions = <
  TData = Awaited<ReturnType<typeof getSkills>>,
  TError = ErrorType<unknown>,
>(
  params?: GetSkillsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getSkills>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSkillsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSkills>>> = ({
    signal,
  }) => getSkills(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSkills>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSkillsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSkills>>
>;
export type GetSkillsQueryError = ErrorType<unknown>;

/**
 * @summary Get all skills
 */

export function useGetSkills<
  TData = Awaited<ReturnType<typeof getSkills>>,
  TError = ErrorType<unknown>,
>(
  params?: GetSkillsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getSkills>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetSkillsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a new skill
 */
export const getCreateSkillUrl = () => {
  return `/api/skills`;
};

export const createSkill = async (
  createSkillRequest: CreateSkillRequest,
  options?: RequestInit,
): Promise<Skill> => {
  return customFetch<Skill>(getCreateSkillUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createSkillRequest),
  });
};

export const getCreateSkillMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSkill>>,
    TError,
    { data: BodyType<CreateSkillRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSkill>>,
  TError,
  { data: BodyType<CreateSkillRequest> },
  TContext
> => {
  const mutationKey = ["createSkill"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSkill>>,
    { data: BodyType<CreateSkillRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createSkill(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateSkillMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSkill>>
>;
export type CreateSkillMutationBody = BodyType<CreateSkillRequest>;
export type CreateSkillMutationError = ErrorType<unknown>;

/**
 * @summary Create a new skill
 */
export const useCreateSkill = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSkill>>,
    TError,
    { data: BodyType<CreateSkillRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createSkill>>,
  TError,
  { data: BodyType<CreateSkillRequest> },
  TContext
> => {
  return useMutation(getCreateSkillMutationOptions(options));
};

/**
 * @summary Get all skill categories
 */
export const getGetSkillCategoriesUrl = () => {
  return `/api/skills/categories`;
};

export const getSkillCategories = async (
  options?: RequestInit,
): Promise<string[]> => {
  return customFetch<string[]>(getGetSkillCategoriesUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetSkillCategoriesQueryKey = () => {
  return [`/api/skills/categories`] as const;
};

export const getGetSkillCategoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getSkillCategories>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSkillCategories>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSkillCategoriesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSkillCategories>>
  > = ({ signal }) => getSkillCategories({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSkillCategories>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSkillCategoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSkillCategories>>
>;
export type GetSkillCategoriesQueryError = ErrorType<unknown>;

/**
 * @summary Get all skill categories
 */

export function useGetSkillCategories<
  TData = Awaited<ReturnType<typeof getSkillCategories>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSkillCategories>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetSkillCategoriesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get mentors matched for a skill
 */
export const getGetMatchedMentorsUrl = (skill: string) => {
  return `/api/match/${skill}`;
};

export const getMatchedMentors = async (
  skill: string,
  options?: RequestInit,
): Promise<MentorMatch[]> => {
  return customFetch<MentorMatch[]>(getGetMatchedMentorsUrl(skill), {
    ...options,
    method: "GET",
  });
};

export const getGetMatchedMentorsQueryKey = (skill: string) => {
  return [`/api/match/${skill}`] as const;
};

export const getGetMatchedMentorsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMatchedMentors>>,
  TError = ErrorType<unknown>,
>(
  skill: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMatchedMentors>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMatchedMentorsQueryKey(skill);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMatchedMentors>>
  > = ({ signal }) => getMatchedMentors(skill, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!skill,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMatchedMentors>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMatchedMentorsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMatchedMentors>>
>;
export type GetMatchedMentorsQueryError = ErrorType<unknown>;

/**
 * @summary Get mentors matched for a skill
 */

export function useGetMatchedMentors<
  TData = Awaited<ReturnType<typeof getMatchedMentors>>,
  TError = ErrorType<unknown>,
>(
  skill: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMatchedMentors>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMatchedMentorsQueryOptions(skill, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get current user's sessions
 */
export const getGetMySessionsUrl = (params?: GetMySessionsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/sessions?${stringifiedParams}`
    : `/api/sessions`;
};

export const getMySessions = async (
  params?: GetMySessionsParams,
  options?: RequestInit,
): Promise<Session[]> => {
  return customFetch<Session[]>(getGetMySessionsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetMySessionsQueryKey = (params?: GetMySessionsParams) => {
  return [`/api/sessions`, ...(params ? [params] : [])] as const;
};

export const getGetMySessionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMySessions>>,
  TError = ErrorType<unknown>,
>(
  params?: GetMySessionsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMySessions>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMySessionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMySessions>>> = ({
    signal,
  }) => getMySessions(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMySessions>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMySessionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMySessions>>
>;
export type GetMySessionsQueryError = ErrorType<unknown>;

/**
 * @summary Get current user's sessions
 */

export function useGetMySessions<
  TData = Awaited<ReturnType<typeof getMySessions>>,
  TError = ErrorType<unknown>,
>(
  params?: GetMySessionsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMySessions>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMySessionsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Book a session with a mentor
 */
export const getBookSessionUrl = () => {
  return `/api/sessions`;
};

export const bookSession = async (
  bookSessionRequest: BookSessionRequest,
  options?: RequestInit,
): Promise<Session> => {
  return customFetch<Session>(getBookSessionUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(bookSessionRequest),
  });
};

export const getBookSessionMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof bookSession>>,
    TError,
    { data: BodyType<BookSessionRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof bookSession>>,
  TError,
  { data: BodyType<BookSessionRequest> },
  TContext
> => {
  const mutationKey = ["bookSession"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof bookSession>>,
    { data: BodyType<BookSessionRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return bookSession(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type BookSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof bookSession>>
>;
export type BookSessionMutationBody = BodyType<BookSessionRequest>;
export type BookSessionMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Book a session with a mentor
 */
export const useBookSession = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof bookSession>>,
    TError,
    { data: BodyType<BookSessionRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof bookSession>>,
  TError,
  { data: BodyType<BookSessionRequest> },
  TContext
> => {
  return useMutation(getBookSessionMutationOptions(options));
};

/**
 * @summary Accept a session request (mentor only)
 */
export const getAcceptSessionUrl = (sessionId: number) => {
  return `/api/sessions/${sessionId}/accept`;
};

export const acceptSession = async (
  sessionId: number,
  options?: RequestInit,
): Promise<Session> => {
  return customFetch<Session>(getAcceptSessionUrl(sessionId), {
    ...options,
    method: "PUT",
  });
};

export const getAcceptSessionMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof acceptSession>>,
    TError,
    { sessionId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof acceptSession>>,
  TError,
  { sessionId: number },
  TContext
> => {
  const mutationKey = ["acceptSession"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof acceptSession>>,
    { sessionId: number }
  > = (props) => {
    const { sessionId } = props ?? {};

    return acceptSession(sessionId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AcceptSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof acceptSession>>
>;

export type AcceptSessionMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Accept a session request (mentor only)
 */
export const useAcceptSession = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof acceptSession>>,
    TError,
    { sessionId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof acceptSession>>,
  TError,
  { sessionId: number },
  TContext
> => {
  return useMutation(getAcceptSessionMutationOptions(options));
};

/**
 * @summary Mark a session as complete
 */
export const getCompleteSessionUrl = (sessionId: number) => {
  return `/api/sessions/${sessionId}/complete`;
};

export const completeSession = async (
  sessionId: number,
  options?: RequestInit,
): Promise<Session> => {
  return customFetch<Session>(getCompleteSessionUrl(sessionId), {
    ...options,
    method: "PUT",
  });
};

export const getCompleteSessionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof completeSession>>,
    TError,
    { sessionId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof completeSession>>,
  TError,
  { sessionId: number },
  TContext
> => {
  const mutationKey = ["completeSession"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof completeSession>>,
    { sessionId: number }
  > = (props) => {
    const { sessionId } = props ?? {};

    return completeSession(sessionId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompleteSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof completeSession>>
>;

export type CompleteSessionMutationError = ErrorType<unknown>;

/**
 * @summary Mark a session as complete
 */
export const useCompleteSession = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof completeSession>>,
    TError,
    { sessionId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof completeSession>>,
  TError,
  { sessionId: number },
  TContext
> => {
  return useMutation(getCompleteSessionMutationOptions(options));
};

/**
 * @summary Cancel a session
 */
export const getCancelSessionUrl = (sessionId: number) => {
  return `/api/sessions/${sessionId}/cancel`;
};

export const cancelSession = async (
  sessionId: number,
  options?: RequestInit,
): Promise<Session> => {
  return customFetch<Session>(getCancelSessionUrl(sessionId), {
    ...options,
    method: "PUT",
  });
};

export const getCancelSessionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelSession>>,
    TError,
    { sessionId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cancelSession>>,
  TError,
  { sessionId: number },
  TContext
> => {
  const mutationKey = ["cancelSession"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cancelSession>>,
    { sessionId: number }
  > = (props) => {
    const { sessionId } = props ?? {};

    return cancelSession(sessionId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CancelSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof cancelSession>>
>;

export type CancelSessionMutationError = ErrorType<unknown>;

/**
 * @summary Cancel a session
 */
export const useCancelSession = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelSession>>,
    TError,
    { sessionId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof cancelSession>>,
  TError,
  { sessionId: number },
  TContext
> => {
  return useMutation(getCancelSessionMutationOptions(options));
};

/**
 * @summary Get current user's wallet balance and transactions
 */
export const getGetWalletUrl = () => {
  return `/api/wallet`;
};

export const getWallet = async (options?: RequestInit): Promise<Wallet> => {
  return customFetch<Wallet>(getGetWalletUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetWalletQueryKey = () => {
  return [`/api/wallet`] as const;
};

export const getGetWalletQueryOptions = <
  TData = Awaited<ReturnType<typeof getWallet>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getWallet>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWalletQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWallet>>> = ({
    signal,
  }) => getWallet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWallet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetWalletQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWallet>>
>;
export type GetWalletQueryError = ErrorType<unknown>;

/**
 * @summary Get current user's wallet balance and transactions
 */

export function useGetWallet<
  TData = Awaited<ReturnType<typeof getWallet>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getWallet>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetWalletQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get wallet transaction history
 */
export const getGetTransactionsUrl = () => {
  return `/api/wallet/transactions`;
};

export const getTransactions = async (
  options?: RequestInit,
): Promise<Transaction[]> => {
  return customFetch<Transaction[]>(getGetTransactionsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetTransactionsQueryKey = () => {
  return [`/api/wallet/transactions`] as const;
};

export const getGetTransactionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getTransactions>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getTransactions>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTransactionsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTransactions>>> = ({
    signal,
  }) => getTransactions({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTransactions>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetTransactionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTransactions>>
>;
export type GetTransactionsQueryError = ErrorType<unknown>;

/**
 * @summary Get wallet transaction history
 */

export function useGetTransactions<
  TData = Awaited<ReturnType<typeof getTransactions>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getTransactions>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetTransactionsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Submit a rating for a completed session
 */
export const getCreateRatingUrl = () => {
  return `/api/ratings`;
};

export const createRating = async (
  createRatingRequest: CreateRatingRequest,
  options?: RequestInit,
): Promise<Rating> => {
  return customFetch<Rating>(getCreateRatingUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createRatingRequest),
  });
};

export const getCreateRatingMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createRating>>,
    TError,
    { data: BodyType<CreateRatingRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createRating>>,
  TError,
  { data: BodyType<CreateRatingRequest> },
  TContext
> => {
  const mutationKey = ["createRating"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createRating>>,
    { data: BodyType<CreateRatingRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createRating(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateRatingMutationResult = NonNullable<
  Awaited<ReturnType<typeof createRating>>
>;
export type CreateRatingMutationBody = BodyType<CreateRatingRequest>;
export type CreateRatingMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Submit a rating for a completed session
 */
export const useCreateRating = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createRating>>,
    TError,
    { data: BodyType<CreateRatingRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createRating>>,
  TError,
  { data: BodyType<CreateRatingRequest> },
  TContext
> => {
  return useMutation(getCreateRatingMutationOptions(options));
};

/**
 * @summary Get all ratings for a mentor
 */
export const getGetMentorRatingsUrl = (mentorId: number) => {
  return `/api/ratings/mentor/${mentorId}`;
};

export const getMentorRatings = async (
  mentorId: number,
  options?: RequestInit,
): Promise<Rating[]> => {
  return customFetch<Rating[]>(getGetMentorRatingsUrl(mentorId), {
    ...options,
    method: "GET",
  });
};

export const getGetMentorRatingsQueryKey = (mentorId: number) => {
  return [`/api/ratings/mentor/${mentorId}`] as const;
};

export const getGetMentorRatingsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMentorRatings>>,
  TError = ErrorType<unknown>,
>(
  mentorId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMentorRatings>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMentorRatingsQueryKey(mentorId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMentorRatings>>
  > = ({ signal }) => getMentorRatings(mentorId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!mentorId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMentorRatings>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMentorRatingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMentorRatings>>
>;
export type GetMentorRatingsQueryError = ErrorType<unknown>;

/**
 * @summary Get all ratings for a mentor
 */

export function useGetMentorRatings<
  TData = Awaited<ReturnType<typeof getMentorRatings>>,
  TError = ErrorType<unknown>,
>(
  mentorId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMentorRatings>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMentorRatingsQueryOptions(mentorId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
