/**
 * Generated by orval v8.5.3
 * Do not edit manually.
 * Api
 * SkillSwap API - Peer-to-peer skill exchange platform
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
  message?: string;
}

export interface RegisterRequest {
  name: string;
  email: string;
  /** @minLength 6 */
  password: string;
  skillsTeach?: string[];
  skillsLearn?: string[];
  referralCode?: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface UserProfile {
  id: number;
  name: string;
  email: string;
  bio?: string | null;
  avatar?: string | null;
  skillsTeach: string[];
  skillsLearn: string[];
  credits: number;
  trustScore: number;
  sessionsCompleted: number;
  averageRating?: number | null;
  sessionPrice?: number | null;
  createdAt: string;
}

export interface AuthResponse {
  token: string;
  user: UserProfile;
  referralCode?: string;
}

export interface UpdateProfileRequest {
  name?: string;
  bio?: string;
  avatar?: string;
  skillsTeach?: string[];
  skillsLearn?: string[];
  sessionPrice?: number;
}

export interface Skill {
  id: number;
  name: string;
  category: string;
  description?: string | null;
  createdBy?: number | null;
  mentorCount: number;
}

export interface CreateSkillRequest {
  name: string;
  category: string;
  description?: string;
}

export interface MentorMatch {
  user: UserProfile;
  matchScore: number;
  skill: string;
  scoreBreakdown?: {
    ratingScore: number;
    sessionsScore: number;
    trustScore: number;
  };
}

export interface BookSessionRequest {
  mentorId: number;
  skill: string;
  scheduledDate: string;
  /** Duration in minutes */
  duration?: number;
  message?: string;
  creditsAmount?: number;
}

export type SessionStatus = (typeof SessionStatus)[keyof typeof SessionStatus];

export const SessionStatus = {
  requested: "requested",
  accepted: "accepted",
  completed: "completed",
  cancelled: "cancelled",
} as const;

export interface Rating {
  id: number;
  sessionId: number;
  mentorId: number;
  studentId: number;
  rating: number;
  review?: string | null;
  studentName: string;
  createdAt: string;
}

export interface Session {
  id: number;
  mentorId: number;
  studentId: number;
  skill: string;
  scheduledDate: string;
  duration: number;
  status: SessionStatus;
  message?: string | null;
  creditsAmount: number;
  meetLink?: string | null;
  mentor: UserProfile;
  student: UserProfile;
  rating?: Rating | null;
  createdAt: string;
}

export interface Wallet {
  balance: number;
  userId: number;
  totalEarned: number;
  totalSpent: number;
}

export type TransactionType =
  (typeof TransactionType)[keyof typeof TransactionType];

export const TransactionType = {
  earned: "earned",
  spent: "spent",
  bonus: "bonus",
  referral: "referral",
  refund: "refund",
  purchased: "purchased",
  withdrawal: "withdrawal",
} as const;

export interface Transaction {
  id: number;
  userId: number;
  /** Positive for credit, negative for debit */
  amount: number;
  type: TransactionType;
  description: string;
  sessionId?: number | null;
  createdAt: string;
}

export interface CreateRatingRequest {
  sessionId: number;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  review?: string;
}

export type GetSkillsParams = {
  category?: string;
  search?: string;
};

export type GetMySessionsParams = {
  role?: GetMySessionsRole;
  status?: GetMySessionsStatus;
};

export type GetMySessionsRole =
  (typeof GetMySessionsRole)[keyof typeof GetMySessionsRole];

export const GetMySessionsRole = {
  mentor: "mentor",
  student: "student",
} as const;

export type GetMySessionsStatus =
  (typeof GetMySessionsStatus)[keyof typeof GetMySessionsStatus];

export const GetMySessionsStatus = {
  requested: "requested",
  accepted: "accepted",
  completed: "completed",
  cancelled: "cancelled",
} as const;