import { pgTable, serial, text, integer, real, timestamp, json } from "drizzle-orm/pg-core";
export const usersTable = pgTable("users", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  bio: text("bio"),
  avatar: text("avatar"),
  skillsTeach: json("skills_teach").$type<string[]>().default([]),
  skillsLearn: json("skills_learn").$type<string[]>().default([]),
  credits: integer("credits").default(200),
  trustScore: integer("trust_score").default(0),
  sessionsCompleted: integer("sessions_completed").default(0),
  averageRating: real("average_rating"),
  pricePerHour: integer("price_per_hour").default(50),
  isAdmin: integer("is_admin").default(0),
  currentStreak: integer("current_streak").default(0),
  longestStreak: integer("longest_streak").default(0),
  lastActiveDate: text("last_active_date"),
  verifiedSkills: json("verified_skills").$type<string[]>().default([]),
  badges: json("badges").$type<string[]>().default([]),
  createdAt: timestamp("created_at").defaultNow(),
});