import { pgTable, serial, integer, text, timestamp, real, varchar, boolean, jsonb } from "drizzle-orm/pg-core";

export const usersTable = pgTable("users", {
  id:                 serial("id").primaryKey(),
  name:               text("name"),
  email:              text("email"),
  passwordHash:       text("password_hash"),
  bio:                text("bio"),
  avatar:             text("avatar"),
  skillsTeach:        text("skills_teach"),
  skillsLearn:        text("skills_learn"),
  credits:            integer("credits").default(50),
  trustScore:         integer("trust_score").default(0),
  sessionsCompleted:  integer("sessions_completed").default(0),
  averageRating:      real("average_rating").default(0),
  createdAt:          timestamp("created_at").defaultNow(),
  pricePerHour:       integer("price_per_hour").default(0),
  isAdmin:            integer("is_admin").default(0),
  currentStreak:      integer("current_streak").default(0),
  longestStreak:      integer("longest_streak").default(0),
  lastActiveDate:     text("last_active_date"),
  verifiedSkills:     jsonb("verified_skills"),
  badges:             jsonb("badges"),
  location:           varchar("location", { length: 100 }),
  microSessionsCount: integer("micro_sessions_count").default(0),
  portfolioPublic:    boolean("portfolio_public").default(true),
  seoSlug:            varchar("seo_slug", { length: 100 }),
  isPremium:          boolean("is_premium").default(false),
  premiumExpiresAt:   timestamp("premium_expires_at"),
  notificationLastSent: timestamp("notification_last_sent"),
  referredBy:         integer("referred_by")
});
